### ISSUE TITLE
ubuntu 环境下没有运行起来

### ISSUE THREAD

**Issue by oatsuper** [reliablejs/reliable-master#27]
Hi 
   希望可以帮忙看下：
reliable/reliable-master 尝试了make build
Hash: 28428221c8a55429afbb
Version: webpack 1.13.1
Time: 4345ms
       Asset     Size  Chunks             Chunk Names
     auth.js  3.78 kB       0  [emitted]  auth
dashboard.js  1.12 MB       1  [emitted]  dashboard
  history.js  1.11 MB       2  [emitted]  history
     home.js  1.11 MB       3  [emitted]  home
    index.js  2.42 kB       4  [emitted]  index
    login.js  3.36 kB       5  [emitted]  login
 password.js  4.49 kB       6  [emitted]  password
   signup.js  3.99 kB       7  [emitted]  signup
     task.js   4.2 kB       8  [emitted]  task
     user.js   1.4 kB       9  [emitted]  user
    + 191 hidden modules
上述是否代表成功呢？

现在的代码更新后，已经没有了make deploy evn=prod 类似命令，尝试Makefile 中的其他命令,例如make server 提示：
 index.js:11:12 [worker:1] pid:16253 mongo error: connect ECONNREFUSED 127.0.0.1:27017

docker 的环境应该是ok的， 
docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
hello-world         latest              723aa7d39e9d        8 days ago          1.848 kB
mongo               latest              282fd552add6        3 weeks ago         336.1 MB
redis               latest              4465e4bcad80        3 weeks ago         185.7 MB

mongo 和redis是手动安装的

此外，
./bin/reliable-master adduser

*****************************************
*  version 1.0.0 is outdate             *
*  run: npm i -g reliable-master@1.0.2  *
*****************************************

 Do you want create an account? [Y/N]y

  User Id: testdemo

此时就一直hung在这个地方，无反应了

还有：
make build-docker
Sending build context to Docker daemon 4.273 MB
Step 1 : FROM reliable-docker-base
Pulling repository docker.io/library/reliable-docker-base
Error: image library/reliable-docker-base not found
make: *** [build-docker] Error 1

**Comment by xudafeng** [comment]
@oatsuper 请按照最新文档部署 http://macacajs.github.io/macaca/master-deployment.html

**Comment by oatsuper** [comment]
好的，谢谢，我稍后进行下最新的部署方式？mac环境必须安装虚拟机么？如果是的话没有看文档提到呀？
此外，偷个懒，就不去macaca中询问了,下方的日志为，我在mac 环境下，进行您的daemo程序，完成login后，出现如下日志打印，谢谢您～
> chromedriver ready with: {"sessionId":null,"status":100,"value":{"message":"chrome not reachable\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X 10.11.2 x86_64)"}}
>> proxy.js:52:14 [master] pid:2368 Proxy: /wd/hub/session/temp/window_handles:GET to http://localhost:9515/wd/hub/session/111855ee16b291017776bdcfbbded544/window_handles:GET with body: {}
>> proxy.js:58:16 [master] pid:2368 Got response with status 200: {"sessionId":"111855ee16b291017776bdcfbbded544","status":6,"value":{"message":"no such session\n  (Driver info: chromedriver=2.20.353124 (035346203162d32c80f1dce587c8154a1efa0c3b),platform=Mac OS X...
>> responseHandler.js:50:12 [master] pid:2368 Send Error Respone to Client: ReferenceError: getErrorByCode is not defined
>> responseHandler.js:56:14 [master] pid:2368 ReferenceError: getErrorByCode is not defined
    at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/.macaca-android_npminstall/macaca-android/1.0.11/macaca-android/lib/helper.js:65:23)
    at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/.macaca-android_npminstall/macaca-android/1.0.11/macaca-android/lib/macaca-android.js:194:18)
    at next (native)
    at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/co/4.6.0/co/index.js:65:19)
    at process._tickCallback (node.js:412:9)

  ReferenceError: getErrorByCode is not defined
      at Object._.sleep._.waitForCondition._.parseWebDriverResult (/usr/local/lib/node_modules/.macaca-android_npminstall/macaca-android/1.0.11/macaca-android/lib/helper.js:65:23)
      at Android.stopDevice.Android.initDevice.data.filter.Android.getWebviews (/usr/local/lib/node_modules/.macaca-android_npminstall/macaca-android/1.0.11/macaca-android/lib/macaca-android.js:194:18)
      at next (native)
      at onFulfilled (/usr/local/lib/node_modules/.macaca-cli_npminstall/co/4.6.0/co/index.js:65:19)
      at process._tickCallback (node.js:412:9)

>>
>>     1) #4 should go into webview
