### ISSUE TITLE
无法使用make adduser添加admin用户以及设置zh_CN无法显示中文

### ISSUE THREAD

**Issue by caoxie** [reliablejs/reliable-master#33]
@xudafeng @zenzhu @yorkie 如题，在common/config.js中，site下的locale设置zh_CN时无效；而且在通过make adduser添加admin用户时，报如下错误：
[root@localhost reliable-master]# make adduser
./bin/reliable-master adduser
module.js:339
    throw err;
    ^

Error: Cannot find module 'co'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/docker/reliable-master/bin/reliable-master:5:12)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
make: *** [adduser] 错误 1

**Comment by yorkie** [comment]
这个是你模块没有正确安装，缺少 co，可以 npm install 一下再试试。BTW，为啥会 at 我呢，纯属好奇～

**Comment by brunoyang** [comment]
@caoxie 请更新到 1.0.4，另外 locale 字段用中划线

**Comment by brunoyang** [comment]
@caoxie  docker exec -it reliable-master make adduser

**Comment by sencho** [comment]
@caoxie 修改中文方法有两种：
1､你build reliable-master镜像前把/reliable-master/common/config.js里的locale修改如下：locale: 'zh-CN'
2、你启动容器后附着进入容器进行修改，重启容器，把浏览器的cookie和缓存清理一下。

添加用户方法也可以附着进入容器的bin目录，reliable-master adduser

**Comment by xudafeng** [comment]
@brunoyang 可以关了吗？
